### ISSUE TITLE
Font size setting is affecting other mods.

### ISSUE THREAD

**Issue by Dunbaratu** [linuxgurugamer/SimpleContractDisplay#1]
I noticed this first with the GUI windows kOS lets scripts make, but then I noticed it also happens to FAR's GUI window too, so it's probably a more general problem.

It seems that when you change Simple Contract Display's Font Size setting, it "leaks" into some part of KSP's standard gui skin so that it changes other mods too.

It appears the effect happens on any type-in fields that use KSP's skin.

I have two screenshots below showing what happens to other mods when I move the font size slider in Simple Contract Display.  (You can test with just FAR's display to use something more familiar.  The effect on kOS is the same as the effect on FAR.  It may affect other mods too, but these were the ones I found it with.)

![screenshot1](https://user-images.githubusercontent.com/5216848/151340648-ebc8533b-0dbe-41c8-95a4-6aa801968929.png)

![screenshot2](https://user-images.githubusercontent.com/5216848/151341024-1b72bfcf-ebd8-4496-96d1-75e5c0da3c62.png)

**Comment by linuxgurugamer** [comment]
Log file please, it has information I need
This was a problem I thought I had fixed in the latest version, without the log, I can't tell which version you are running

**Comment by linuxgurugamer** [comment]
Oh, I see from the picture you are running the latest release

**Comment by linuxgurugamer** [comment]
I've confirmed the issue with FAR, I can't figure out how to use KoS :-)

But it appears to be the same, so I'll use the FAR window to test

**Comment by linuxgurugamer** [comment]
Fixed and released, thank you
